### PR TITLE
Prettier/Eslint setup

### LINKED ISSUE #45: Add automatic prettier-formatting when committing files?
Hey all, I spoke to Kevin about this, but since we're using Prettier for code formatting, would anyone be against the idea of having a pre-commit hook to automatically have Prettier format files before they're committed to the repo? It would go a long way in maintaining consistent formatting throughout the codebase.

I was thinking of going with **Option 1** referenced [here](https://prettier.io/docs/en/precommit.html).

### PR DESCRIPTION
**Pull request by jhuynh85**
Adds the following functionality:

1. Automatically runs `prettier --write` on committed files
2. Automatically displays lint warnings/errors when using the `gatsby develop` command

Adds the following packages:

1. **`eslint`** - Base ESLint package
2. **`eslint-config-airbnb`** - Airbnb lint rules
3. **`eslint-config-prettier`** - Turns off all rules that are unnecessary or might conflict with Prettier
4. **`eslint-plugin-import`** - From @appleJax's ESLint config
5. **`eslint-plugin-jsx-a11y`** - From @appleJax's ESLint config
6. **`eslint-plugin-react`** - From @appleJax's ESLint config
7. **`babel-eslint`** - From @appleJax's ESLint config
8. **`gatsby-plugin-eslint`** - Allows displaying linting errors while running `gatsby develop`
9. **`eslint-loader`** - Required for `gatsby-plugin-eslint`
10. **`husky`** - For Prettier precommit hook
11. **`lint-staged`** - For Prettier precommit hook

Closes #45

### CODE REVIEW

**Comment by jhuynh85** [comment]
This PR took a little longer than I expected, let me know if you guys want me to squash the commits into one!

**Comment by appleJax** [comment]
@jhuynh85 great work! I pushed some commits with the following changes:
- update the husky config according to https://github.com/typicode/husky (apparently husky is deprecating the `precommit` script) 
- change `.eslintrc` to `.eslintrc.js` because prettier was formatting the `.eslintrc` file in a weird way
- alphabetize `.eslintrc.js` to make rules easier to find
- add `.editorconfig` to standardize indent style/size, line-feeds, trim whitespace, etc
- use 80-char line limit and prefer double quotes (they are easier to read - this way we can type single quotes and read double quotes)
- add `eslint-plugin-prettier` to get `formatOnSave` working

@jhuynh85 and anyone else, please pull down the latest changes and play around with making new commits to ensure we like the current configuration.

**Comment by appleJax** [comment]
After playing around with prettier, I feel like we'd be better off without it. ESLint will format things in a sane way. I feel like prettier is too heavy-handed and does not allow you to customize it. @jhuynh85 let me know what you think about removing prettier.

**Comment by jhuynh85** [comment]
Either way works for me. As long as we have some way to enforce consistent code style I'm happy 👍

**Pull request merged**
